### ISSUE TITLE
Fails to create new bookmark

### ISSUE THREAD

**Issue by jcharaoui** [bookieio/bookie-firefox#26] opened 2014-10-18 17:58 UTC
This error appears in the server log when trying to create a bookmark using the extension.

```
StatementError: invalid literal for int() with base 10: 'false' (original cause: ValueError: invalid literal for int() with base 10: 'false') u'INSERT INTO bmarks (hash_id, description, extended, stored, updated, clicks, is_private, inserted_by, username, tag_str) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' [{'username': u'jerome', 'updated': None, 'extended': u'', 'description': u'XIA', 'inserted_by': u'firefox_ext', 'tag_str': u'', 'is_private': u'false', 'hash_id': u'3ab797ff5caba6'}]
```

**Comment by widox** [comment] 2014-11-06 02:53
I'm unable to reproduce this issue. Was this with the most recent version 0.5.0 of the extension, and are you still seeing this issue?

**Comment by mitechie** [comment] 2014-12-22 19:49
closing as incomplete, I've uploaded a new 0.6 version that has been qa'd to work correctly. if there are issues with that release please reopen for file a new bug.

**Closed as completed by mitechie** 2014-12-22 19:49 UTC
